trigger:
- main

pool:
  name: myagent

variables:
- group: terraform-secrets
- name: TF_VERSION
  value: '1.6.6'

stages:

- stage: Terraform
  jobs:
  - job: Deploy
    steps:

    # =========================
    # Install Terraform
    # =========================
    - script: |
        sudo apt update -y
        sudo apt install -y unzip wget

        wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
        unzip terraform_$(TF_VERSION)_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

        terraform -version
      displayName: "Install Terraform"

    # =========================
    # Terraform Init
    # =========================
    - script: |
        terraform init
      workingDirectory: "$(System.DefaultWorkingDirectory)/azure-.2tier-terraform-python"
      displayName: "Terraform Init"

    # =========================
    # Terraform Validate
    # =========================
    - script: |
        terraform validate
      workingDirectory: "$(System.DefaultWorkingDirectory)/azure-.2tier-terraform-python"
      displayName: "Terraform Validate"

    # =========================
    # Terraform Plan (SERVICE CONNECTION USED PROPERLY)
    # =========================
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-service'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logged in via Service Connection"

          cd $(System.DefaultWorkingDirectory)/azure-.2tier-terraform-python

          terraform plan \
            -var="admin_password=$(admin_password)" \
            -var="mysql_password=$(mysql_password)" \
            -out=tfplan
      displayName: "Terraform Plan"

    # =========================
    # Terraform Apply
    # =========================
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-service'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(System.DefaultWorkingDirectory)/azure-.2tier-terraform-python
          terraform apply -auto-approve tfplan
      displayName: "Terraform Apply"